smtpd/filestore.go
Hi @jhillyerd 
I've made a hotfix for issue #35.
Regards,
Tomasz
=> Hotfix for #35 Log error and continue when deleting oldest message fails.

doc/config.md, pkg/config/config.go, pkg/server/smtp/handler.go, pkg/server/smtp/listener.go
This adds support for opportunistic TLS connections for SMTP-only. Clients that follow the RFC of:
```
S: 220 inbucket Inbucket SMTP ready
C: EHLO openssl.client.net
S: 250-Great, let's get this show on the road
S: 250-8BITMIME
S: 250-STARTTLS
S: 250 SIZE 10240000
C: STARTTLS
S: 220 STARTTLS
C: <starts TLS negotiation>
C & S: <negotiate a TLS session>
C & S: <check result of negotiation>
C: EHLO nowhere.tld
. . .
```
This feature is **disabled** by default.
To generate x509 certs:
```bash
$ openssl req -x509 -sha256 -newkey rsa:2048 -keyout certificate.key -out certificate.crt -days 1024 -nodes
```
Run inbucket with TLS Enabled (the default private key is **cert.key** and default public key is **cert.crt**) -- you can change these with environmental variable also:
```bash
$ …
```
=> Opportunistic TLS Support

Dockerfile
Use the INBUCKET_WEB_ADDR value to get het port number of Inbucket using 'cut'. If the variable is not set, use the default value (and that is 0.0.0.0:9000). Healtcheck will check the exit code of the command executed (0=HEALTY)
=> Added a healthcheck to the Dockerfile

.gitignore, pkg/server/web/handlers.go, pkg/server/web/server.go, ui/public/index-dev.html, ui/public/index.html, ui/webpack.config.js
- Create a new index-dev.html for webpack live server
- Update Go+index.html to set `<base href>`
- Fixes #171
=> Set base path in index.html

pkg/server/web/handlers.go
Hi
I am using Inbucket in my dev stack, and got a failure during a security scan due to click-jacking.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
Here is my fix for this.
Thanks for the great project
=> Avoid potential click jacking

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
Resolves: #62 
Added support for LOGIN and PLAIN auth methods. Any credentials are accepted.
=> Add support for AUTH

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
- handler: Don't fail on 8 character command lines
=> Fix command line length bug

Dockerfile, shell.nix
Our current build downloads the amd64 elm binary and runs it in an arm container.  This works on GitHub due to it being an emulated environment, but on a native arm device fails with:
```
ERROR in ./src/Main.elm
Module build failed (from ./node_modules/elm-webpack-loader/index.js):
Compiler process exited with error Error attempting to run Elm compiler "elm":
Error: spawn Unknown system error -8
```
Marking the frontend build as amd64 will cause it to execute much faster on GitHub, and resolve issues migrating from webpack to parcel (#260), which is very picky about it's arm environment.  Our Dockerfile will continue to fail on native arm devices, but they will still be able to pull our prebuilt images.
=> Docker frontend build runs as amd64

CHANGELOG.md, etc/dev-start.sh, etc/swaks-tests/run-tests.sh, pkg/policy/address.go, pkg/policy/address_test.go, pkg/server/smtp/handler_test.go, pkg/test/integration_test.go, pkg/test/testdata/no-to-ipv4.golden, pkg/test/testdata/no-to-ipv6.golden, pkg/test/testdata/no-to.txt
Handle IP address domains for #243.  Also adds support for forward-path routes in RCPT TO.
Given both of these rework how RCPT TO addresses are parsed, this PR has potential for unintended consequences.
=> Handle IP address domains

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go
Debugging SMTP handler sessions is difficult, as all the logs for all tests were being sent to the terminal when any test failed.  This change uses zerolog functionality to collect logs for a particular test and log it to testing.T.
- smtp: allow logger to be passed into startSession
- smtp: remove logbuf and teardown from handler_test
- smtp: handler_test log output to testing.T
=> Refactor SMTP handler_test log collection

cmd/inbucket/main.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go
- Do drain logging from main to reduce test output
- smtp: Break up some of the larger handler test funcs
=> Break up handler tests

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
Previously inbucket only recognized AUTH=<> at the end of the RCPT FROM arg
list, this was an error.  Should resolve #283
=> smtp: Adjust fromRegex to handle AUTH=<> in middle of args

pkg/extension/luahost/bind_address.go, pkg/extension/luahost/bind_message.go, pkg/extension/luahost/bind_policy.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go
Adds our first two Lua function bindings, as well as some datatypes for them to
use.
=> lua: Bind after_message_stored and before_mail_accepted

pkg/extension/luahost/bind_address.go, pkg/extension/luahost/bind_message.go, pkg/extension/luahost/lua_test.go
- lua: update bind_message to use table syntax
- lua: update bind_address to use table syntax
=> lua: Use table syntax for user object bindings

.goreleaser.yml
.Binary was causing some archives to be called inbucket_client
For #341 and just correctness in general
=> goreleaser: correct archive naming by using default

pkg/extension/async_broker.go, pkg/extension/async_broker_test.go, pkg/extension/broker.go, pkg/extension/host.go, pkg/extension/luahost/lua.go, pkg/message/manager_test.go, pkg/msghub/hub.go, pkg/test/storage_suite.go
=> extension: split out an async specific broker for "after" events

pkg/msghub/hub.go, pkg/msghub/hub_test.go
=> msghub: Clear deleted messages instead of unlinking

.goreleaser.yml
Our manually configured template was breaking debian package snapshots,
version must start with a number
=> goreleaser: use default snapshot name template

.goreleaser.yml
=> goreleaser: remove deprecated rlcp option

pkg/server/web/server.go
=> web: Redirect base path `prefix` to `prefix/`

pkg/config/config.go, pkg/server/smtp/handler.go, pkg/server/smtp/listener.go
When this is enabled, the server listens with TLS instead of waiting for STARTTLS.
=> Add a ForceTLS flag for SMTP.

pkg/server/smtp/handler.go
This change makes all header timestamps (e.g. "Received") to use
UTC time zone.
This way the length of such headers do not depend on local time zone
which if effect fixes https://github.com/inbucket/inbucket/issues/404.
=> UTC format timestamps in headers (#404)

.github/workflows/docker-build.yml
Docker builds, particularly ARM, take a long time.  This workflow change should
allow them to be run manually, and automatically after a PR is submitted.
=> docker: don't build until after PR submitted

pkg/extension/broker.go, pkg/extension/event/events.go, pkg/extension/host.go, pkg/message/manager.go, pkg/message/manager_test.go, pkg/server/smtp/handler_test.go, pkg/test/testdata/basic.golden, pkg/test/testdata/encodedheader.golden, pkg/test/testdata/fullname.golden, pkg/test/testdata/no-to-ipv4.golden, pkg/test/testdata/no-to-ipv6.golden
- extension: add InboundMessage type and bindings
- manager: fires BeforeMessageStored event
- manager: Reacts to BeforeMessageStored event response
- manager: Apply BeforeMessageStored response fields to message
Closes #408
=> extension: BeforeMessageStored event to rewrite envelope

pkg/policy/address.go, pkg/server/smtp/handler_test.go, pkg/stringutil/utils.go, pkg/stringutil/utils_test.go
I propose an update to my previous PR: add reject from origin domain feature #375
In this PR, I propose a new feature to check origin smtp domain against a list that can contains joker characters (* and ?).
=> Reject invalidomain with wildcards

.github/workflows/docker-build.yml
=> docker-build action: only push to registry on main branch and v* tag pushes

pkg/message/manager.go, pkg/message/manager_test.go
=> message: Prefer To header for BeforeMessageStored event

pkg/extension/event/events.go, pkg/extension/luahost/bind_inboundmessage.go, pkg/extension/luahost/bind_inboundmessage_test.go, pkg/extension/luahost/lua_test.go, pkg/message/manager.go, pkg/message/manager_test.go
To ease conversions to/from MessageMetadata
=> event: Use pointers for InboundMessage addresses

pkg/storage/file/fstore.go, pkg/test/storage_suite.go
Some file handles were not being closed.  I also made some of the tests more readable.
For #450
=> storage test: fix failures on windows

pkg/rest/client/apiv1_client.go, pkg/rest/client/apiv1_client_opts.go, pkg/rest/client/apiv1_client_test.go
The rest client does not currently allow a user to pass options, such as a custom transport. This PR extends the `client.New` function to allow for custom options to be passed
=> [Rest Client] Use options for client.New

pkg/rest/client/rest.go, pkg/rest/client/rest_test.go
resolves #476 
I have done this globally, but potentially it could be better to have an option when creating the rest client to decide. But when creating the client, we base the "base" url, which to me means it can be more than schema and hostname.
Let me know what you think!
=> [Rest Client] changing to enable relative urls

pkg/rest/client/example_test.go
=> chore: rework client example to omit log.Fatal, breaks defer

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go
- chore: colocate SMTP session WaitGroup incr/decr
- fix: smtp tests that hang on panic/t.Fatal
- chore: reorder smtp/handler test helpers
=> fix: prevent smtp/handler test from freezing on panic

.golangci.yml, shell.nix
golangci-lint's default linters are too permissive
closes #485
=> actions: configure golangci linters

.github/workflows/lint.yml
=> fix: skip-pkg-cache no longer supported by golangci-lint

.golangci.yml
=> chore: disable deprecated execinquery linter

pkg/extension/luahost/lua.go
=> fix: ls.Get calls use top-relative index

pkg/extension/event/events.go, pkg/extension/host.go, pkg/extension/luahost/bind_inbucket.go, pkg/extension/luahost/bind_smtpsession.go, pkg/extension/luahost/bind_smtpsession_test.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go, pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
- Add `SMTPSession` type for extensions
- Define & wire `BeforeRcptToAccepted` event
- Define `inbucket.before.rcpt_to_accepted` lua handler
=> feat: Add Before RCPT TO Accepted event
