smtpd/filestore.go, smtpd/filestore_test.go
fixes: https://github.com/jhillyerd/inbucket/issues/50
=> add option to get the latest message using latest as request parameter

themes/bootstrap/public/mailbox.js, themes/bootstrap/templates/mailbox/index.html
fixes: https://github.com/jhillyerd/inbucket/issues/55
=> add option to delete the mailbox from the UI

themes/bootstrap/public/mailbox.js, themes/bootstrap/public/monitor.js
This is a proposal to display newest messages first.
=> Reverse message display sort order

doc/config.md
=> Fix INBUCKET_STORAGE_PARAMS example

doc/config.md, pkg/config/config.go, pkg/policy/address.go, pkg/policy/address_test.go
See #139 for previous version (breaking contributing rules!)
=> Add ability to name mailboxes after domain of email

Dockerfile, etc/docker/defaults/greeting.html, etc/docker/defaults/start-inbucket.sh
Updated the Dockerfile to create a user and group 'Inbucket'. Set the permissions on the various files and directories. Updated the start-inbucket.sh script to not copy the greeting.html to the config directory (related to this, changed the default greeting.html file to the one in the defaults directory).
Fixes #27
=> Docker image should run non-root

Dockerfile, etc/docker/defaults/greeting.html, etc/docker/defaults/start-inbucket.sh
=> Rollback #153 as it breaks storage volumes, closes #27

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
This PR will allow to use <> as MAIL FROM: parameter.
Closes #164
=> allow empty envelope

ui/src/Api.elm, ui/src/Effect.elm, ui/src/Main.elm, ui/src/Page/Home.elm, ui/src/Page/Mailbox.elm, ui/src/Page/Monitor.elm, ui/src/Page/Status.elm, ui/src/Timer.elm
This is the first phase of the implementation and refactor.  All pages now leverage Effects for most of their Session and Cmd requests.  More work required for routing and other lingering Cmd use.
=> ui: Add an Effect system to handle global state and Elm Cmds

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
This reverts commit 261bbef4262b6b3a6841e3abc87f76984dab0fb8.  It was merged directly into master by mistake.
=> Revert "Add support for AUTH, closes #62"

.goreleaser.yml
=> goreleaser: update nfpm config to use contents attrib

ui/src/mailbox.css, ui/src/main.css, ui/src/navbar.css
Updates the css to support dark mode via media query.
The dark theme its heavily inspired on the new dark mode for google.com. The light theme it's unchanged.
=> Adds dark mode support

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
=> Format fixes

pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
=> smtp: allow empty user & pass during AUTH LOGIN

ui/package-lock.json, ui/package.json
- bump node deps
- npm audit fix
=> Upgrade node deps

.github/workflows/docker-build.yml
=> Update to docker-push-action v2 w/ metadata, buildx

.goreleaser.yml
Include missing files in tar, deb, and rpm packages, fixes #249
=> Correct goreleaser config

ui/package-lock.json
=> Update npm deps

.github/workflows/docker-build.yml, .github/workflows/release.yml, CHANGELOG.md, CONTRIBUTING.md, README.md
- Update contributing guide, remove git-flow references
- Update changelog for main branch rename
- Update github actions for branch rename
- Update README build badges
- Update README for new branch names
- Note branch rename in change log
=> Rename master branch to main

.goreleaser.yml
Re: https://github.com/inbucket/inbucket/issues/246
👋  This should start building ARM and ARM64 builds. I'm not familiar with goreleaser myself but this seems to follow their example in the docs https://goreleaser.com/customization/build/
=> Add arm and arm64 builds

.github/workflows/docker-build.yml
Build both ARMv7 and ARM64 docker images using QEMU
=> Add support for ARMv7 and ARM64 docker images

etc/swaks-tests/run-tests.sh, ui/package.json, ui/src/index-dev.html, ui/src/index.html, ui/src/index.js
- Fix error in swaks tests server default env var
- Fix non-root basepaths, closes #273
=> Fix non-root basepaths

CHANGELOG.md
=> Update CHANGELOG for 3.0.3

pkg/test/storage_suite.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> delete minor unreachable code caused by t.Fatal

cmd/inbucket/main.go, pkg/msghub/hub.go, pkg/msghub/hub_test.go, pkg/rest/testutils_test.go, pkg/server/lifecycle.go, pkg/server/pop3/listener.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go, pkg/server/web/server.go, pkg/storage/retention.go, pkg/storage/retention_test.go, pkg/test/integration_test.go
Refactor server life-cycle into it's own file, make service startup and monitoring more consistent and testable.
This should be helpful for testing hooks, #280
=> Dependency injection improvements

.github/workflows/build-and-test.yml, .github/workflows/release.yml, Dockerfile, etc/docker/docker-run.sh
=> Build with Go 1.19

Makefile
=> Makefile: fix, wasn't testing SRC timestamps

shell.nix
=> shell.nix: Add gopls as build dep

pkg/extension/broker.go, pkg/extension/broker_test.go
EventBroker provides an interface between Inbucket and extensions.
For #280 #309
=> extension: Implement an EventBroker

pkg/extension/event/events.go, pkg/extension/host.go, pkg/message/manager.go, pkg/msghub/hub.go, pkg/msghub/hub_test.go, pkg/rest/socketv1_controller.go, pkg/server/lifecycle.go, pkg/test/integration_test.go
* Replace existing direct StoreManager->msghub communication with this
event
* For #280 #309 #312 #310
=> extension: Add MessageStored event

pkg/extension/broker_test.go
=> Fix incorrect test capitalization

pkg/message/manager.go, pkg/message/manager_test.go
=> manager: Test that MessageStored event is emitted

pkg/extension/event/events.go, pkg/extension/host.go, pkg/server/lifecycle.go, pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go, pkg/test/integration_test.go
=> extension: Add BeforeMailAccepted event

doc/config.md, go.mod, go.sum, pkg/config/config.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go, pkg/extension/luahost/pool_test.go, pkg/server/lifecycle.go
=> lua: Init with config and pool

pkg/extension/luahost/bind_address_test.go, pkg/extension/luahost/bind_message_test.go
=> lua: Add getter/setter tests for bound objects

pkg/extension/event/events.go, pkg/message/manager.go, pkg/message/message.go, pkg/rest/apiv1_controller_test.go, pkg/storage/file/fstore_test.go, pkg/storage/retention_test.go, pkg/test/manager.go, pkg/test/storage_suite.go
=> Replace message.Metadata usage with event.MessageMetadata

.gitignore, pkg/extension/broker.go, pkg/extension/host.go, pkg/message/manager.go, pkg/server/lifecycle.go, pkg/storage/file/fstore.go, pkg/storage/file/fstore_test.go, pkg/storage/file/mbox.go, pkg/storage/mem/store.go, pkg/storage/mem/store_test.go, pkg/storage/storage.go, pkg/test/integration_test.go, pkg/test/storage_suite.go, shell.nix
For #332
- Ignore test lua script
- Wire ExtHost into storage system imports
- storage/file: emit deleted events
- storage/mem: emit deleted events
=> storage: emit AfterMessageDeleted events

pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go
- lua: tidy test helpers
- lua: test after_message_deleted func
for #332
=> delete event: test lua func

pkg/msghub/hub.go
=> msghub: Recover and log panics

pkg/msghub/hub.go, pkg/msghub/hub_test.go, pkg/rest/model/apiv1_model.go, pkg/rest/socketv1_controller.go, ui/src/Data/MonitorEvent.elm, ui/src/Page/Monitor.elm
Does not yet handle purging mailboxes
For #332 and #181
=> feat: Monitor tab dynamically updates when messages are deleted

pkg/storage/file/fstore.go, pkg/storage/mem/store.go, pkg/test/storage_suite.go
=> file & mem stores should emit delete events on purge

.github/workflows/build-and-test.yml, .github/workflows/docker-build.yml, .github/workflows/release.yml
=> GHA: Use node16 actions, Go 1.20

ui/yarn.lock
=> ui: update browser list

.goreleaser.yml
=> goreleaser: set archive rlcp true to mirror upcoming default

doc/config.md
=> Fix doc name for LUA config param

pkg/extension/luahost/bind_inbucket.go, pkg/extension/luahost/bind_inbucket_test.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go, shell.nix
- Expose inbucket.after.message_stored in lua
- Expose inbucket.after.message_deleted in lua
- Expose inbucket.before.mail_accepted in lua
=> Provide `inbucket` object in Lua

pkg/extension/luahost/lua_test.go, pkg/message/manager.go
=> events: Remove unnecessary go calls

CHANGELOG.md
=> Update changelog for 3.1.0 beta1

.github/workflows/build-and-test.yml, .github/workflows/docker-build.yml, .github/workflows/release.yml, Dockerfile, go.mod
- update go.mod to 1.20
- clean up and format ci jobs
- update go and alpine images in dockerfile
=> Few updates in ci jobs and go.mod/dockerfile

cmd/inbucket/main.go
=> add version flag

.gitignore, pkg/config/config.go, pkg/policy/address.go, pkg/rest/testutils_test.go, pkg/server/lifecycle.go, pkg/server/pop3/handler.go, pkg/server/pop3/handler_test.go, pkg/server/pop3/listener.go, pkg/server/smtp/handler_test.go, pkg/webui/root_controller.go
This implements the STLS command for POP3.
=> Implement STLS for pop3.

.goreleaser.yml, etc/linux/inbucket.service
- service: fix ExecStart path for pre-built packages
- packaging: fix goreleaser and service paths
Fixes for #363
=> Fix service paths

README.md
=> README: Fix docker image link

etc/swaks-tests/mime-inline.raw, etc/swaks-tests/run-tests.sh, pkg/message/message.go, pkg/rest/apiv1_controller_test.go
=> message: Include inlines when returning attachments

Dockerfile
=> Fix docker build workflow

go.mod, go.sum, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go, pkg/extension/luahost/pool_test.go
Allows Lua scripts to add entries to Inbuckets log
Closes #327
=> lua: Expose logger object

pkg/extension/luahost/lua.go
=> lua: fix incorrect function name

pkg/message/manager.go
=> smtp: Use enmime.DecodeHeaders for better performance

pkg/message/manager.go, pkg/message/manager_test.go, pkg/server/smtp/handler.go
Preparation for before storage events, #408
=> message: migrate more delivery logic into manager.go

pkg/message/manager_test.go
=> message: Add test for recipient policy

pkg/extension/luahost/bind_inboundmessage.go, pkg/extension/luahost/bind_inboundmessage_test.go, pkg/extension/luahost/bind_inbucket.go, pkg/extension/luahost/bind_inbucket_test.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/extension/luahost/pool.go
- lua: Restore missing test log output
- lua: Use logger for test assert_async output
- lua: add InboundMessage bindings
- lua: bind BeforeMessageStored function
For #408
=> lua: bind BeforeMessageStored function

shell.nix, ui/yarn.lock
=> ui: update elm dep

ui/package.json, ui/yarn.lock
- ui: update parcel dep
- ui: update parcel-namer-rewrite dep
=> ui: update parcel deps

ui/yarn.lock
=> ui: update webcomponentsjs dep

ui/src/Data/ServerConfig.elm, ui/src/Page/Status.elm
=> ui: status: Display reject-origin-domains config

doc/config.md
=> doc: add INBUCKET_SMTP_REJECTORIGINDOMAINS docs

.github/workflows/docker-build.yml
Fixes syntax errors introduced by #426
=> docker-build action: fix, use .env syntax

pkg/message/manager_test.go
=> message: Verify empty mailbox list does not error

Makefile, pkg/stringutil/utils.go
=> stringutil: fix golint comment format error

pkg/rest/apiv1_controller_test.go, pkg/rest/client/apiv1_client_test.go, pkg/rest/client/example_test.go, pkg/rest/client/rest.go, pkg/rest/socketv1_controller.go, pkg/rest/socketv2_controller.go
=> rest: resolve linter errors

cmd/client/list.go, cmd/client/main.go, cmd/client/match.go, cmd/client/mbox.go
=> client: resolve linter errors

pkg/storage/mem/store_test.go, pkg/storage/retention_test.go
=> storage: resolve linter errors

pkg/server/pop3/handler_test.go, pkg/server/pop3/listener.go, pkg/server/smtp/handler.go, pkg/server/smtp/listener.go, pkg/server/web/server.go
=> server: resolve linter errors

pkg/server/lifecycle.go
Current Notify() method could lead to multiple combined-channels being created,
and it would be undefined on which would receive an error notification.
=> lifecycle: Don't create multiple notify channels

pkg/extension/luahost/lua.go, pkg/msghub/hub.go, pkg/policy/address.go, pkg/webui/sanitize/html.go
- webui: resolve linter errors
- msghub: resolve linter errors
- policy: resolve linter errors
- extension: resolve linter errors
=> various: resolve linter errors in a number of pkgs

pkg/extension/luahost/bind_inboundmessage.go, pkg/extension/luahost/bind_message.go
=> luahost: add type check TODOs

.github/workflows/build-and-test.yml
=> github actions: test coverage on pushes to main

.github/workflows/lint.yml
=> github actions: work around golangci errors

.github/workflows/lint.yml
=> github actions: fix for #441, skip-pkg-cache: true

pkg/test/storage_test.go
=> test: Add tests for StoreStub

pkg/test/storage.go, pkg/test/storage_test.go
=> test: impl StoreStub.MarkSeen

pkg/test/storage.go, pkg/test/storage_test.go
=> test: impl StoreStub.PurgeMessages

pkg/message/manager_test.go
=> message: improve manager test coverage

pkg/storage/file/fstore.go
=> storage: fail startup if unable to create file store dir

pkg/test/integration_test.go
Windows can't listen to network ports without it
For #450
=> test: preserve SYSTEMROOT on windows

.gitattributes
Resolve golden file line ending issues for #450
=> git: do not treat golden files as text

doc/config.md, pkg/storage/file/fstore.go, pkg/storage/file/fstore_test.go
=> storage: $ can be used in place of : in filestore path

.github/workflows/build-and-test.yml
=> actions: test build on windows

pkg/rest/client/apiv1_client_opts.go
=> rest/client: fix comment lint error

.github/workflows/release.yml, Dockerfile, etc/dev-start.sh, shell.nix, ui/package.json
=> node: 20.x

ui/package.json, ui/yarn.lock
=> yarn/js: update parcel & deps

ui/package.json, ui/yarn.lock
=> yarn/js: flexible version specs

CHANGELOG.md
=> update changelog for 3.1.0-beta2

.github/dependabot.yml
=> actions: add dependabot config

.github/workflows/lint.yml
=> actions: lint on push to any branch

cmd/client/mbox.go, pkg/config/config.go, pkg/extension/async_broker.go, pkg/extension/host.go, pkg/message/manager.go, pkg/message/manager_test.go, pkg/policy/address.go, pkg/policy/address_test.go, pkg/rest/client/rest_test.go, pkg/rest/routes.go, pkg/server/pop3/handler.go, pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go, pkg/server/web/server.go, pkg/storage/lock.go, pkg/storage/lock_test.go, pkg/storage/mem/store.go, pkg/stringutil/utils.go, pkg/webui/sanitize/css_test.go
- fix whitespace warnings
- fix a number of typos
- fix many cosmetic linter warnings
For #485
=> chore: fix many cosmetic linter warnings

cmd/inbucket/main.go, pkg/extension/async_broker_test.go, pkg/extension/broker_test.go, pkg/extension/luahost/bind_inboundmessage.go, pkg/extension/luahost/lua.go, pkg/policy/address.go, pkg/rest/apiv1_controller.go, pkg/rest/client/apiv1_client.go, pkg/server/pop3/listener.go, pkg/server/smtp/handler.go, pkg/storage/file/mbox.go, pkg/webui/root_controller.go
=> chore: fix more capitalization style warnings

pkg/extension/luahost/pool_test.go, pkg/message/manager_test.go, pkg/server/smtp/handler_test.go, pkg/storage/file/fstore_test.go, pkg/test/storage_suite.go, pkg/test/storage_test.go
=> chore: fix many unit test style warnings

pkg/extension/luahost/lua.go, pkg/server/lifecycle.go
=> luahost: use sentinel ErrNoScript

cmd/client/main.go, cmd/inbucket/main.go, pkg/policy/address.go, pkg/policy/address_test.go, pkg/rest/testutils_test.go, pkg/server/pop3/handler.go, pkg/server/smtp/handler.go, pkg/storage/file/mbox.go, pkg/webui/sanitize/html.go
=> chore: many small lint/perf fixes

pkg/storage/mem/store.go, pkg/test/storage_helpers.go, pkg/test/storage_suite.go
=> storage_suite: refactor to use common struct param

pkg/message/manager.go, pkg/message/manager_test.go, pkg/msghub/hub.go, pkg/policy/address.go, pkg/rest/client/apiv1_client_opts.go, pkg/rest/client/rest.go, pkg/rest/client/rest_test.go, pkg/server/web/handlers.go, pkg/server/web/helpers.go, pkg/server/web/server.go, pkg/test/integration_test.go
=> chore: more small lint/perf fixes

pkg/server/smtp/handler_test.go
=> chore: refactor playSession etc to use t.Fatal

pkg/storage/file/fstore_test.go
=> fstore: remove redundant test helper

cmd/client/list.go, cmd/client/match.go, cmd/client/mbox.go, pkg/rest/client/apiv1_client.go, pkg/rest/client/rest.go, pkg/rest/client/rest_test.go
- rest/client: add WithContext methods
- cmd/client: pass context
Also for #485
=> feature: Context support for REST client

pkg/rest/testutils_test.go
=> chore: fix testutils linter warnings

pkg/server/smtp/handler.go
- chore: convert smtp/handler if-else chain to switch-case
- chore: extract long case into parseMailCmd func
- chore: remove extraneous braces in cases
For #485
=> chore: refactor smtp/handler if-else chain

pkg/test/integration_test.go, pkg/test/storage_suite.go
- fix: future naming collision, suite -> storeSuite
- chore: migrate integration to testify/suite
For #485
=> chore: migrate integration to testify/suite

pkg/stringutil/utils.go, pkg/stringutil/utils_test.go, pkg/test/integration_test.go
- chore: faster hash to string conv
- chore: require NoError in integration test setup
For #485
=> chore: two small lint fixes

pkg/server/pop3/handler_test.go
=> chore: refactor proto tests to use ReadDotLines

pkg/server/pop3/listener.go, pkg/server/smtp/handler_test.go, pkg/server/smtp/listener.go
=> chore: fix linter warnings

go.mod, go.sum, pkg/message/manager.go, pkg/message/message.go, pkg/rest/apiv1_controller_test.go
=> chore: use enmime 2.0

pkg/extension/luahost/bind_address_test.go, pkg/extension/luahost/bind_inboundmessage_test.go, pkg/extension/luahost/bind_inbucket_test.go, pkg/extension/luahost/bind_message_test.go, pkg/extension/luahost/lua_test.go, pkg/test/lua.go
Create a lua test helper, improve assert messages
=> chore: create Lua test helper

.github/workflows/release.yml, .goreleaser.yml
=> chore: update goreleaser to v2

.github/workflows/build-and-test.yml
=> chore: test build UI outside of release

pkg/extension/host.go, pkg/extension/luahost/bind_inbucket.go, pkg/extension/luahost/bind_inbucket_test.go, pkg/extension/luahost/lua.go, pkg/extension/luahost/lua_test.go, pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
- **chore: rename BeforeMailAccepted to BeforeMailFromAccepted**
- **chore: update BeforeMailAccepted to use SMTPSession**
=> chore: Update BeforeMailAccepted

pkg/extension/event/events.go, pkg/extension/luahost/bind_smtpsession.go, pkg/extension/luahost/bind_smtpsession_test.go, pkg/server/smtp/handler.go, pkg/server/smtp/handler_test.go
=> feat: Add RemoteAddr to SMTPSession

.github/workflows/build-and-test.yml, .github/workflows/lint.yml, .github/workflows/release.yml, Dockerfile
=> chore: Build with Go 1.23

Dockerfile
=> chore: Modernize Docker ENV statements

CHANGELOG.md
=> release 3.1.0-beta3

.golangci.yml
=> Update expired linters

.github/workflows/build-and-test.yml, .github/workflows/lint.yml, .github/workflows/release.yml, Dockerfile, shell.nix
=> chore: Build with Go 1.24

.github/workflows/lint.yml, .golangci.yml, pkg/server/pop3/handler.go, pkg/server/smtp/handler.go, pkg/test/manager.go, pkg/test/storage_suite.go
- **Update to golangci lint 2.0.x**
- **Fix new lint warnings**
=> chore: Update golangci lint to 2.0.x
